from dragonfly import MappingRule, Key

class KeyRule(MappingRule):

    mapping = {
            'bang': Key('!'),
            'at': Key('@'),
            'hash': Key('#'),
            'dollar': Key('$'),
            'percent': Key('percent'),
            'carrot': Key('^'),
            'amper': Key('&'),
            'star': Key('*'),
            'paren': Key('('),
            'right paren': Key(')'),
            'minus': Key('minus'),
            'under': Key('underscore'),
            'plus': Key('+'),
            'tick': Key('`'),
            'tilde': Key('~'),
            'square': Key('['),
            'right square': Key(']'),
            'curly': Key('{'),
            'right curly': Key('}'),
            'backslash': Key('\\'),
            'slash': Key('slash'),
            'pipe': Key('|'),
            'colon': Key('colon'),
            'semi': Key(';'),
            'single': Key("'"),
            'double': Key('"'),
            'comma': Key(','),
            'dot': Key('.'),
            'angle': Key('<'),
            'right angle': Key('>'),
            'question': Key('?'),
            'equal': Key('='),
            'left': Key('left'),
            'right': Key('right'),
            'up': Key('up'),
            'down': Key('down'),
            'enter': Key('enter'),
            'tab': Key('tab'),
            'space': Key('space'),
            'junk': Key('backspace'),
            'delete': Key('delete'),
            'escape': Key('escape'),
            'page up': Key('pgup'),
            'page down': Key('pgdown')
    }
